### PR TITLE
Added support for relative paths, `__dirname` no longer necessary

### PR DESCRIPTION
**Pull request by seymar**
I thought needing to specify the absolute path of the directory shouldn't be necessary.
So I added support for relative paths & backwards compatibility with the old absolute paths.

### CODE REVIEW

**Comment by dougwilson** [comment]
Unfortunately this does not work. I believe you misunderstand how `module.parent.filename` works--if you required the same `require-all` instance, both requires will have the same `module.parent.filename` value, even if those requires occurred from completely different locations.

**Comment by seymar** [comment]
I don't see in what case that would be a problem? Could you provide a simple test code that makes it fail?

**Comment by dougwilson** [comment]
I'll try to write up an example next week or so :)

**Comment by dougwilson** [comment]
It should be pretty easy, though: Make two directories a and b. Then put two files in there that require this module and try to use relative require within those directories. Then make one file that requires a and b. Now this module will end up with the module.parent.filename both as the file in the a directory, breaking what the b file expected.

**Comment by seymar** [comment]
Thanks! You were right, it's because the required modules are cached.
But I managed to find a work around by getting the caller using stack trace. Maybe you can reopen the PR so I can attach my new code.

How important is it that the module works on old Node versions?
0.6
0.8
0.10

**Comment by dougwilson** [comment]
So yes, you can use them, but that is just too fragile for me to accept, sorry!

> How important is it that the module works on old Node versions?

Required, as I use this module with things that run in 0.6 and later.

**Comment by dougwilson** [comment]
Sorry, I didn't complete my thoughts :) If you can support Node.js 0.6, 0.8, 0.10, etc. with this, I would like to see it, to understand what it does to see how feasible it is. The reopen button on this PR is disabled for me, so feel free to open that as a new PR.

**Pull request closed without merging**
