### PR TITLE
Allow loading custom files by overriding `require`

### PR DESCRIPTION
**Pull request by Redsandro**
Allow loading custom files by overriding `require`. E.g. loading pictures into binary data or `yaml` files into objects.

```javascript
var fs = require('fs');
var yaml = require('js-yaml');
var config = require('require-all')({
  dirname     :  __dirname + '/config',
  filter      : /^([^\.].*)\.y(a?)ml?$/,
  recursive   : true,
  override    : function (file) {
    return yaml.safeLoad(fs.readFileSync(file, 'utf8'));
  }
});
```

### CODE REVIEW

**Comment by Redsandro** [comment]
Shoot, node `0.6` compatibility for tests?
Hmm.. I better make a different test.

**Comment by Redsandro** [comment]
@dougwilson sorry for the extra commits. I had to figure out a test simple enough (no dev-dependencies) to pass `0.6` testing.

With this minor addition comes great power. I hope you'll consider merging.

**Comment by dougwilson** [comment]
Perhaps "load", "loader" or similar instead of "override" for the option name.

**Comment by Redsandro** [comment]
@dougwilson
> Perhaps "load", "loader" or similar 

Done.

> Please remove the version bumps.

And done. Note that this instruction:

> This file is a manually maintained list of changes for each release. Feel free
to add your changes here when sending pull requests.

It encourages doing a version bump with a commit, because one cannot file a change under a non-existing version.

**Comment by dougwilson** [comment]
Hi @Redsandro sorry for the confusion :) I didn't mean you couldn't add to the change log, just not to do a version bump. For example, there are currently some PRs in the queue, and they may be released under 2.2.0 prior to this merge, and then I'd need to wait for you to update your PR to then be able to merge it, etc. Also, the release itself is based on making a commit bumping the `package.json` file, so I wouldn't be able to perform the normal release process, further holding up being able to merge.

I apologize I have not been able to provide better instructions regarding creating a PR.

**Comment by Redsandro** [comment]
@dougwilson Got it. So I unbumped the version, but the commits still touch `package.json`. How would you like me to proceed? Can I safely squash all commits and force-push to my forked branch? Will it automatically truncate commits in this PR? (Never tried that on PR.) Or should I create a new PR with everything squashed?

**Comment by Redsandro** [comment]
Alternatively, you can tell github to squash these commits before merge.

squash

**Comment by Redsandro** [comment]
@dougwilson I'm sad to see that you didn't release this with **2.2.0**. I satisfied all your requests 3 months ago, and I was waiting for a release.

Is this going to happen? I'm not looking forward to merging in master every time something changed.

If this is not in line with the scope of your project, that's fair. Just please let me know so I can look for a different solution.

**Comment by dougwilson** [comment]
I am just merging the PRs in chronological order. I didn't yet have time to resolve the conflicts for your PR is all, so I thank you for doing so.

I tried to explain a 2.2.0 would be released before your change above, so I'm sorry if that wasn't clear to you. Please let me know how I could have been more transparent in my intentions.

I wrote:

> there are currently some PRs in the queue, and they may be released under 2.2.0 prior to this merge, and then I'd need to wait for you to update your PR to then be able to merge it

**Comment by Redsandro** [comment]
@dougwilson I'm sorry for misunderstanding. I didn't see how one PR would break another (my) PR since the edits seemed unrelated. Your intent would be clearer if you pointed out where specifically you saw conflicts, because otherwise I just make assumptions as to your thoughts: I assumed - please excuse me for being such a pessimist, it's not personal, just my general attitude - that you didn't check but just assumed there would be a conflict. And consequently you would merge this when observed there was no code conflict.

I got impatient. I'm sorry. Take your time. I'm using commit `4524de8` in my `package.conf` directly.

**Comment by dougwilson** [comment]
Sorry, until I merged the other PR into master, GitHub didn't tell me there would be conflicts or not, so I didn't know until that was done. If there is a method I can know ahead of time, please point me how so I can provide the feedback to where the conflicts are located :) !

**Comment by Redsandro** [comment]
@dougwilson said:
> If there is a method I can know ahead of time, please point me how

Through the power of developer-ray-vision. :stuck_out_tongue: The `filter` and `require` functionality is completely different. Git(hub) will automatically merge as many commits as you want on top of each other, as long as there are no changes on the same lines. This rarely is the case when PR's aren't changing the same functions.

For example, the PR you merged effectively changes [one line](https://github.com/felixge/node-require-all/commit/8fc63160561e8c055c10dd9275513d18b92c966e#diff-168726dbe96b3ce427e7fedce31bb0bc) in `filterFile()`. My PR is not related to `filterFile()`. 

Are there more PR's queued?

**Comment by dougwilson** [comment]
That's what I thought too, but then I'm not sure why GitHub blocked the merged button on this PR before saying there were conflicts...

**Comment by Redsandro** [comment]
Hmm.. it was probably a conflict in the changelog where I had appended this PR. I thought there was an option to pick only relevant files. Perhaps I was mistaken.

Looking forward, tell me if there's anything I can do.

**Comment by Redsandro** [comment]
@dougwilson can we get this merged now?

**Comment by Redsandro** [comment]
@dougwilson... I'm slowly dying. Please publish.

**Comment by dougwilson** [comment]
Thanks for the ping. I'm going to resolve this conflict so you're not staying waiting. Thanks for the feature, but I'm not interested in adding it. I feel it is breaking the fundamental identify of the module "require-all" being that it simply "require()" all the matching files.

Just publish your changes as your own module as I can link to it as an alternative.

**Comment by Redsandro** [comment]
Thanks for clarifying. That's unfortunate. I don't agree with your premise. The small (optional) addition enables one to require-all as opposed to require-some. E.g. require-all the yaml-files to build a configuration object. Literally "simply require()ing all the matching files", but with support for custom files. In my opinion the patch fits perfectly with the identity of this module.

However, your module, your veto.

My intention was commiting back to improve on this handy little module so people can easily work around the fact that node doesn't open yaml files as easy as json files (which it supports out of the box), but I am not interested in maintaining a public fork for this. If people want it, [here it is](https://github.com/Redsandro/node-require-all/tree/de100648a3d52a4ad241184c42f5ecba7defa8b3#loader-require).

Thanks for the update! Now I can rest.

**Comment by dougwilson** [comment]
Node.js does allow you to open YAML files with the built in "require()" all you have to do is register a require hook. Then this module can load them since require() itself can.

**Comment by dougwilson** [comment]
Add `require('require-yaml')` in your app and now require-all can load YAML files.

**Pull request closed without merging**
