### PR TITLE
Pass name and filepath to resolve function

### PR DESCRIPTION
**Pull request by seymar**
As a solution for Issue #28 I added a parameter to the resolve function containing info about the required module.

### CODE REVIEW

**Comment by seymar** [comment]
I added tests and simplified the feature a bit, by just passing the property name and path. Less is more.

**Comment by seymar** [comment]
Hmm what else do you want to test about them?
Never used tests before, just barely figured out that `assert` module :-)

**Comment by dougwilson** [comment]
Their contents need to be validated. For example, what is `path` supposed to contain? is it the absolute path or the relative path? Does it include the file name or not? Should it have a trailing directory separator or no? If someone changes one of those things, it would be a breaking change, and these tests wouldn't catch a change to any one of those questions.

**Comment by seymar** [comment]
Thanks! I'll implement it.

**Comment by seymar** [comment]
Checking the paths against the absolute paths now.

**Comment by seymar** [comment]
I might be able to test it on Windows tomorrow. I'll take a look.

**Comment by seymar** [comment]
I can't seem to reproduce any fails, what errors do you get?

**Comment by seymar** [comment]
Features of v2.1.0 are now also in here + did some minor aesthetic improvements

**Comment by dougwilson** [comment]
Looks like this is unnecessary to solve the referenced issue, as the explanation of what was wanted is already how this module works.

**Pull request closed without merging**
