### PR TITLE
Resolve includes file name.

### PR DESCRIPTION
**Pull request by jaimegomez**
Added the file name as a 2nd argument to resolve.
Expanded resolve test with 3rd case that test the name.

### CODE REVIEW

**Comment by KristjanTammekivi** [comment]
*bump*, really missing this feature

**Comment by dougwilson** [comment]
Hey, sorry I didn't see this. Can you explain this pull request some more? I see you wrote "Added the file name as a 2nd argument to resolve." but that's not what's in this change. `match[1]` is simply the first capture group in the regular expression, which can be anything, not just the file name.

Can you online the use-case you are trying to solve with this pull request?

Also, can you add documentation to the README for the feature that this pull request is adding?

**Comment by KristjanTammekivi** [comment]
I can't speak for the guy who made the PR, but for me it goes as follows:

I have a folder commands, which contains, well, API commands for the module. I use resolve to wrap them in the same wrapper function. This part works fine. However, when I wanted to add some trace logging in the lines of command "command name" was called with arguments "xyz", I found that there was no beautiful way of doing that. So temporarily I moved the logging into the commands themselves.

**Comment by dougwilson** [comment]
Hi @KristjanTammekivi very interesting. I'm not sure if I understood what you are doing, though. Perhaps would you be able to whip up the code you would use pretending like this PR was merged? That may help me understand. Currently this PR doesn't actually add any information you cannot already get at, it's just embedded in the full file path in the first argument.

Can you also speak towards the implementation question as well? The PR says it's adding the file name to the arguments, but it's actually adding `match[1]`, not the `file` variable. Which one are you expecting?

**Comment by jaimegomez** [comment]
Since the resolve is run recursively, `match[1]` is effectively the file name (without the `.js` extension, not captured by the `DEFAULT_FILTER`).

And the first argument of `resolve` only contains whatever it is in the respective `module.export` variable, so the file path is not embedded there.

I already documented my use case :) forgot to add a reference: [Could be useful if resolve includes file name](https://github.com/felixge/node-require-all/issues/36).

Knowing which file are you working with (during resolve) can be extremely useful; in my case is because files have semantic meaning, they carry the desired name of the task so I don't have to repeat it. And for this other guy, I imagine this is what he wants to do (using my code as the example):

```javascript
var gulp = require('gulp');

require('require-all')({
    dirname: __dirname + '/src/gulp',
    resolve: function(item, name) {
        gulp.task(name, item.deps, function(cb) {
            console.log(`Running task: ${name}...`);
            item.task(cb);
        });
    },
});
```

Which looks pretty good to me!

I'll amend the README first chance I get :)

**Comment by dougwilson** [comment]
Hi @jaimegomez your example isn't very helpful; this module is not a directly walking module; you should not be using the module for side-effects. I don't see you using the return value anywhere.

**Comment by dougwilson** [comment]
Your example should be the following:
```js
var gulp = require('gulp');

var tasks = require('require-all')(dirname: __dirname + '/src/gulp);

Object.keys(tasks).forEach(function(name) {
    var item = tasks[name];
    gulp.task(name, item.deps, function(cb) {
        console.log(`Running task: ${name}...`);
        item.task(cb);
    });
});
```
Or similar.

**Comment by jaimegomez** [comment]
You're right, I had forgotten about that; tried it a long time ago, before switching to using `resolve` (and bumping into this issue). Why? I guess it's only because it fits my coding style better, looks "simpler" to me, more straight-forward, and most of the code that I use works in a similar fashion.

I'm sure, based on the previous comments, that @KristjanTammekivi would use it the way I described, though I don't know his motivation.

But I get what you're saying, this can already be accomplished just using the language, and `resolve` was never intended to be used this way, so it doesn't make sense from that perspective.

If I had to argue in favor of this change, I'd say that it adds flexibility (as we can see in this thread), but I agree that's not necessarily a good thing. Your call!

**Comment by dougwilson** [comment]
I'm al for adding flexibility, but adding a dozen ways to do the same things ends up as a bloated API. If someone has the need for the file name or something in the `resolve` function, we can add it, but I don't see the case for it currently. And this PR doesn't even add the filename, it adds `match[1]`, which is even less useful (though it's hard to judge that without understanding the use-cases).

Maybe if you can use lodash or similar, at least until `Object.entries` is part of the language?
```js
_.each(require('require-all')(__dirname + '/src/gulp'), function(item, name) {
    gulp.task(name, item.deps, function(cb) {
        console.log(`Running task: ${name}...`);
        item.task(cb);
    });
});
```

**Comment by jaimegomez** [comment]
While we're at it, I have a question, what else could we find in the `match[1]` result? You've mentioned a few times that it's not the file name, but I can't see what you mean; it's already been used as the key value for `modules` (assuming `map` is not overridden), which is touted as the file name in the documentation.

But I'm convinced, this change only makes sense if we added `each` as a function and use it instead, but then again, why not use the tools we already have in the language.

Guess I'll keep using my private repo for now :) the resulting code just looks beautiful in my eyes.

**Comment by dougwilson** [comment]
> which is touted as the file name in the documentation.

Where does it say that? I would like to correct that if it says somewhere it is the file name.

**Comment by dougwilson** [comment]
> While we're at it, I have a question, what else could we find in the match[1] result?

It is simply whatever the user specified as the first capture group in the `filter` option. Yes, it comes from the file name, but it's just a part of the file name, not the actual file name (or even the entire name minus the extension). It's whatever the first capture group captured. I believe PR #31 is even trying to make that be the result of some function, making it more likely to not be the file's name.

**Comment by dougwilson** [comment]
> this change only makes sense if we added each as a function and use it instead, but then again, why not use the tools we already have in the language.

I'm not sure what you mean by this. Can you elaborate?

**Comment by jaimegomez** [comment]
Oh right, you can change the filter, I was missing that completely.

Line 48 (redacted): "...The `map` function is called on both file and directory names...".

As for adding `each` as a function, I was thinking on this:

```javascript
var gulp = require('gulp');

require('require-all')({
    dirname: __dirname + '/src/gulp',
    each: function(key, value) {
        // exactly what I want
    },
});
```

It'd be a convenience method, I recon there are other ways to accomplish the same thing (you have mentioned three already). But it's also not unheard of 😄

**Comment by dougwilson** [comment]
Yep:
```js
_.each(require('require-all')(__dirname + '/src/gulp'), function(item, name) {
    gulp.task(name, item.deps, function(cb) {
        console.log(`Running task: ${name}...`);
        item.task(cb);
    });
});
```

**Pull request closed without merging**
